# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:40
from __future__ import unicode_literals

from django.db import migrations

from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fstmobile', '0008_auto_20160715_0218'),
        ('fstmobile', '0008_auto_20160711_1917'),
    ]

    operations = [
    ]
