# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fstmobile', '0035_auto_20160829_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 12, 21, 57, 835446, tzinfo=utc), editable=False, verbose_name=b'auto_now_add=true'),
        ),
    ]
