# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fstmobile', '0037_auto_20160829_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 12, 39, 59, 859219, tzinfo=utc), editable=False, verbose_name=b'auto_now_add=true'),
        ),
    ]
