# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fstmobile', '0040_auto_20160829_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 12, 0, 50, 580017, tzinfo=utc), editable=False, verbose_name=b'auto_now_add=true'),
        ),
    ]
