# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fstmobile', '0050_auto_20160915_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 15, 25, 15, 606755, tzinfo=utc), editable=False, verbose_name=b'auto_now_add=true'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 15, 25, 15, 599160, tzinfo=utc), editable=False, verbose_name=b'auto_now_add=true'),
        ),
    ]
